// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6T9wG8fuSsyTfJWrdWOcftCXaginDIbQ',
    appId: '1:752604547682:web:def521d00f64e4fcc05f3b',
    messagingSenderId: '752604547682',
    projectId: 'renergy-63921',
    authDomain: 'renergy-63921.firebaseapp.com',
    storageBucket: 'renergy-63921.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKK7iUxQ_T9EZH1dPrmL_uc6U3RVdJnMs',
    appId: '1:752604547682:android:6e6d8813ac5aa7edc05f3b',
    messagingSenderId: '752604547682',
    projectId: 'renergy-63921',
    storageBucket: 'renergy-63921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyz1byAmTF7V6Q-TnQE5sZV-i-rlWLXn8',
    appId: '1:752604547682:ios:c6c54a4b7ebeb576c05f3b',
    messagingSenderId: '752604547682',
    projectId: 'renergy-63921',
    storageBucket: 'renergy-63921.firebasestorage.app',
    iosBundleId: 'com.example.renergyApp',
  );
}
